# Тема 10. Декораторы и исключения

Отчет по Теме #10 выполнил:

- Харченко Владислав Андреевич
- АИС-22-1

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ |---|
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи. P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

```python
from functools import lru_cache


@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
    
    
if __name__ == '__main__':
    print(fibonacci(100))
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Lab10_91.png "8.1")
### Выводы.
Функция с декоратором работает в разы быстрее, засчет подтягивания промежуточных данных из кэша.

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.
```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]
        
        if age < 0 or age > 130:
            age = "Недопустимый возраст"
        input_func(name, age)
    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")
      
if __name__ == "__main__":
    personal_info("Владимир", 38)
    personal_info("Александр", -5)
    personal_info("Петр", 138, 15, 48, 2)
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Lab10_92.png "8.2")
### Выводы.
Реализуем декоратор с проверкой граничных значений возраста.


## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.
```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print("Вся информация обработана")
        
        
if __name__ == "__main__":
    data([1,15,"Hello","i","try","to","crash","your", "site", 38, 45])
```

### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Lab10_93.png "8.3")

### Выводы.
Создадим декоратор для проверки значений типа int и исключений значений типа string.

## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”.
```python
class NegativeValueException(Exception):
    pass


def check_name(name):
    if len(name) > 10:
        raise NegativeValueException("Длина больше 10 символов")
    else:
        print("Успешная регистрация")
        

if __name__ == "__main__":
    name = "12345678910"
    check_name(name)
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Lab10_94.png "8.4")
### Выводы.
Реализуем декоратор с проверкой длины имени.

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.
```python
class SiteChecker:
    def __init__(self, func):
        print("> Класс SiteChecker метод __init__ успешный запуск")
        self.func = func
    
    def __call__(self):
        print("> Проверка перед запуском", self.func.__name__)
        self.func()
        print("> Проверка безопасного выключения")
        
@SiteChecker
def site():
    print("Усердная работа сайта")
    
if __name__ == "__main__":
    print(">> Сайт запущен")
    site()
    print(">> Сайт выключен")
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Lab10_95.png "8.5")
### Выводы.
Реализуем самописный логгер и встроим его в функцию с помощью декоратора.

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
```python
import time

def execution_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"\n\nExecution time of {func.__name__}: {end_time - start_time} seconds")
        return result
    return wrapper

@execution_time
def fibonacci():
    fib1 = fib2 = 1
    
    for i in range(2, 200):
        fib1,fib2=fib2,fib1+fib2
        print(fib2, end=' ')
        
        
if __name__ == "__main__":
    fibonacci()
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Sam10_1.png "8.1")
### Выводы.
Реализован класс Weather с атрибутами даты и температуры. Внутри класса есть метод прогноза погоды. Создаем экземпляр класса и вызываем метод report().

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.
```python
import os
from contextlib import contextmanager

class EmptyFileError(Exception):
    pass


@contextmanager
def open_file(filename, mode):
    file = open(filename, mode)
    yield file
    file.close()


def read_file(filename):
    with open_file(f"{filename}", "r") as f:
        if os.stat(f"{filename}").st_size == 0:
            raise EmptyFileError("Файл пустой")
        content = f.read()
        print(content)
        
        
read_file("text.txt")
read_file("empty.txt")
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Sam10_2.png "8.2")
### Выводы.
К классу, определенному заданием выше, добавлен метод date_report, указывающий дату, исходя из атрибута экзмепляра класса.


## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.
```python
def data(num):
    try:
        result = 2 + num
        print(result)
    except TypeError as ex:
        print(ex)
        

if __name__ == "__main__":
    data(2)
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Sam10_3.png "8.3")
### Выводы.
Реализовано наследование, путем дочернего класса Forecast.

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.


```python
def type_check(param_types):
    def decorator(func):
        def wrapper(*args, **kwargs):
            for arg, param_type in zip(args, param_types):
                if not isinstance(arg, param_type):
                    raise TypeError(f'Аргумент {arg} не соответствует типу {param_type.__name__}')
            return func(*args, **kwargs)  
        return wrapper
    return decorator

@type_check((int, int))
def add(a, b):
    return a + b

@type_check((str, str)) 
def concatenate(str1, str2):
    return str1 + str2

if __name__ == "__main__":
    print(f'Сумма 5 и 10: {add(5, 10)}') 
    print(f'Объединение: {"Hello, "} {"world!"}: {concatenate("Hello, ", "world!")}')
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Sam10_4.png "8.4")
### Выводы.
- Декоратор type_check: Принимает кортеж, содержащий ожидаемые типы аргументов.
  - Метод decorator: Оборачивает исходную функцию.
  - Метод wrapper: Проверяет типы переданных аргументов. Если тип не совпадает, выбрасывает исключение TypeError.
- Функция add: Сложение двух чисел. Ожидает, что оба аргумента будут типа int.
- Функция concatenate: Объединяет две строки. Ожидает, что оба аргумента будут типа str.
- Пример использования: В блоке if __name__ == "__main__": мы вызываем обе функции с корректными аргументами. 

## Самостоятельная работа №5
### Самостоятельно реализуйте полиморфизм. Он должен отличаться, от того, что указан в теоретическом материале (методичке) и лабораторных заданиях. Результатом выполнения задания будет листинг кода и получившийся вывод консоли.
```python
import math

class NegativeNumberError(Exception):
    pass

def calculate_square_root(num):
    if num < 0:
        raise NegativeNumberError("Ошибка: нельзя вычислить квадратный корень из отрицательного числа.")
    return math.sqrt(num)

def calculate_factorial(num):
    if num < 0:
        raise NegativeNumberError("Ошибка: факториал нельзя вычислить для отрицательного числа.")
    if num == 0:
        return 1
    result = 1
    for i in range(1, num + 1):
        result *= i
    return result


try:
    print(f'Квадратный корень из 16: {calculate_square_root(16)}')
    print(f'Факториал числа 5: {calculate_factorial(5)}')
    print(f'Квадратный корень из -4: {calculate_square_root(-4)}')
except NegativeNumberError as e:
    print(e)

try:
    print(f'Факториал числа -3: {calculate_factorial(-3)}')
except NegativeNumberError as e:
    print(e)
```
### Результат.
![Изображение](https://github.com/Wottajotta/Software_engineering/blob/Тема_10/pic/Sam10_5.png "8.5")
### Выводы.
1. Мы создаём собственное исключение NegativeNumberError, наследуя от базового класса Exception. Это исключение будет использоваться для обработки случаев, когда вводится отрицательное число.
2. Определяем функцию calculate_square_root, которая вычисляет квадратный корень чисел. Если число отрицательное, вызывает NegativeNumberError.
3. Определяем функцию calculate_factorial, которая вычисляет факториал числа. Она также вызывает NegativeNumberError, если число отрицательное.
4. В блоках try-except проверяем результат выполнения обеих функций. Если происходит исключение, оно перехватывается и выводится на экран.
5. В первой попытке мы вызываем обе функции с валидными числами, а затем пытаемся вызвать их с отрицательными числами, чтобы посмотреть, как работает исключение.


## Общие выводы по теме
Рассмотрели декораторы/исключение и опробовали их на практике